### ISSUE TITLE
[!] No podspec found for `flutter_uae_pass` in `.symlinks/plugins/flutter_uae_pass/ios`

### ISSUE THREAD

**Issue by karthiktheboss** [MohamedAbd0/uae_pass#1]
Hi @MohamedAbd0 
I'm able to execute the application in android version and it is successful. But when I try install pod for iOS Version I'm getting this error  

> [!] No podspec found for `flutter_uae_pass` in `.symlinks/plugins/flutter_uae_pass/iOS`

**Comment by Developeritt1203** [comment]
I am also getting the same issue.  
    -> Fetching podspec for `flutter_uae_pass` from `.symlinks/plugins/flutter_uae_pass/ios`
    [!] No podspec found for `flutter_uae_pass` in `.symlinks/plugins/flutter_uae_pass/ios`

**Comment by MohamedAbd0** [comment]
@karthiktheboss @Developeritt1203 
Hi everyone, I am sorry for this conflict.
I solved it in the new [version](https://pub.dev/packages/flutter_uae_pass) `flutter_uae_pass: ^0.0.2`
now you can update the package and continue.
