### ISSUE TITLE
Urgent: Critical Issue in Production Environment

### ISSUE THREAD

**Issue by ahmedahel** [MohamedAbd0/uae_pass#2]
Dear Mohammed,

I hope this message finds you well.

First and foremost, I want to express my gratitude for your exceptional library.

However, I am currently encountering a critical issue in our Production Environment that requires immediate attention.

The problem arises when calling the getProfile function, as it returns an exception: 

[https://ids.uaepass.ae/authenticationendpoint/oauth2_error.do?oauthErrorCode=invalid_client&oauthErrorMsg=application.not.found]

Upon investigation, I discovered that the getProfile function is calling the production URL with incorrect parameters:

URL: [https://ids.uaepass.ae/oauth2/authorize?ui_locales=en&scope=urn%3Auae%3Adigitalid%3Aprofile&acr_values=urn%3Adigitalid%3Aauthentication%3Aflow%3Amobileondevice&response_type=code&redirect_uri=https%3A%2F%2Foauthtest.com%2Fauthorization%2Freturn&state=YLN0AKt7oj1JheV7QXti8ZJo&client_id=sandbox_stage]

The issue lies in the client_id parameter being set to "sandbox_stage," which is incorrect. I have verified that the correct client_id is not "sandbox_stage."

I urgently request your assistance in debugging and resolving this issue as soon as possible.

Thank you for your prompt attention to this matter.

Warm regards,

**Comment by ahmedahel** [comment]
Note : The above issue happened on android platform Only

**Comment by ahmedahel** [comment]
Note : On IOS Platform some of data coming null (fullnameEN,fullnameAR) , but when I call the api via postman it's return the correct data and not null

**Comment by MohamedAbd0** [comment]
Thank you for finding this pug and your solution for this pug, I appreciate your help, 
I wish to contact you in the future.
