### ISSUE TITLE
App getting closed when click on cancel option in uae pass webview, or when authentication is declined from uae pass

### ISSUE THREAD

**Issue by amitkumartiwaridis** [MohamedAbd0/uae_pass#7]
D/AndroidRuntime(16201): Shutting down VM
E/AndroidRuntime(16201): FATAL EXCEPTION: main
E/AndroidRuntime(16201): Process: com.dis.sharafexchange, PID: 16201
E/AndroidRuntime(16201): java.lang.NullPointerException
E/AndroidRuntime(16201): 	at ae.sdg.libraryuaepass.UAEPassAuthenticationDialog$initView$1.shouldOverrideUrlLoading(UAEPassAuthenticationDialog.kt:123)
E/AndroidRuntime(16201): 	at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
E/AndroidRuntime(16201): 	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.aab-stable-642216533:129)
E/AndroidRuntime(16201): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(16201): 	at android.os.MessageQueue.next(MessageQueue.java:350)
E/AndroidRuntime(16201): 	at android.os.Looper.loopOnce(Looper.java:187)
E/AndroidRuntime(16201): 	at android.os.Looper.loop(Looper.java:368)
E/AndroidRuntime(16201): 	at android.app.ActivityThread.main(ActivityThread.java:8848)
E/AndroidRuntime(16201): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16201): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
E/AndroidRuntime(16201): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
@MohamedAbd0

**Comment by MohamedAbd0** [comment]
Make sure you are already adding the app schema name to make the UAE Pass App Reopen your app again

**Comment by amitkumartiwaridis** [comment]
> Make sure you are already adding the app schema name to make the UAE Pass App Reopen your app again

in iOS is working fine, only Android having issue. i shared the log of android build

**Comment by abqamar** [comment]
Hi @amitkumartiwaridis,
If your redirect URI is test://myapp then add below scheme in AndroidManifest.xml

<data
                    android:host="myapp"
                    android:scheme="test" />
